apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-yaml
  template:
    metadata:
      labels:
        app: my-web-yaml
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-web-yaml-svc
spec:
  type: NodePort
  selector:
    app: my-web-yaml
  ports:
  - port: 80
    targetPort: 80
